import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  label: {
    fontSize: 20,
    top: 10,
    height: 40,
    padding: 5,
    color: 'white',
    backgroundColor: '#66FF99',
    borderColor: '#66FF99',
    borderWidth: 2,
    minWidth: '30%',
    maxWidth: '30%',
  },
  inputContainer: {
    top: 10,
    borderColor: '#66FF99',
    borderWidth: 2,
    height: 40,
    minWidth: '70%',
    maxWidth: '70%',
  },
  input: {
    top: 5,
    padding: 0,
    paddingLeft: 5,
    fontSize: 18,
  },
  row: {
    flexDirection: 'row',
    marginHorizontal: 15,
  },
  column: {
    flexDirection: 'column',
  },
  idBoardContainer: {
    margin: 10,
    padding: 10,
    backgroundColor: '#FFFFFFAA',
  },
  idBoard: {
    marginTop: 10,
  },
  avatar: {
    width: 80,
    height: 80,
    margin: 10,
    borderWidth: 6,
    borderColor: '#66FF99',
    borderRadius: 20,
  },
  username: {
    margin: 10,
    marginBottom: 2,
    fontSize: 26,
    color: '#444444',
    fontWeight: 'bold',
  },
  quote: {
    marginLeft: 10,
    fontSize: 16,
    color: '#999999',
  },
  editBtn: {
    marginTop: 10,
    marginLeft: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    marginRight: 90,
    fontSize: 16,
    color: 'white',
    backgroundColor: '#66FF99',
  },
  flwNum: {
    marginHorizontal: 10,
    fontSize: 16,
    color: '#444444',
  },
  flwLbl: {
    marginRight: 60,
    fontSize: 16,
    color: '#999999',
  },
  ansSelect: {
    paddingHorizontal: 45,
    paddingVertical: 10,
    backgroundColor: '#FFFFFFAA',
  },
  qaCard: {
    backgroundColor: 'white',
    margin: 8,
    padding: 8,
    borderRadius: 8,
    flexDirection: 'column',
  },
  qaCardText: {
    fontSize: 16,
    marginLeft: 5,
  },
  detailCard: {
    marginVertical: 18,
    marginHorizontal: 8,
    borderRadius: 16,
    flexDirection: 'column',
    backgroundColor: 'white',
    paddingHorizontal: 20,
  },
  detailCardText: {
    alignSelf: 'center',
    marginTop: 40,
    marginBottom: 30,
    fontWeight: 'bold',
    fontSize: 20,
  },
  detailCardTime: {
    marginLeft: 12,
    marginBottom: 4,
  },
  answerTip: {
    marginLeft: 12,
    marginTop: 4,
    fontSize: 18,
  },
  answerInputBox: {
    textAlignVertical: 'top',
    textAlign: 'left',
    borderWidth: 1,
    borderColor: '#999999',
    height: 200,
    marginHorizontal: 10,
    marginBottom: 10,
    fontSize: 18,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  openButton: {
    backgroundColor: '#F194FF',
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  registerTip: {
    fontSize: 18,
    marginVertical: 5,
  },
  registerInput: {
    fontSize: 18,
    borderWidth: 1,
    padding: 1,
    marginVertical: 5,
  }
});
